/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.customer_issues.tempdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Temp1 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`temp1`")
public class Temp1 implements Serializable {

    private Integer id;
    private String lang;
    private Integer val1;
    private Integer val2;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`lang`", nullable = true, length = 255)
    public String getLang() {
        return this.lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    @Column(name = "`val1`", nullable = true, scale = 0, precision = 10)
    public Integer getVal1() {
        return this.val1;
    }

    public void setVal1(Integer val1) {
        this.val1 = val1;
    }

    @Column(name = "`val2`", nullable = true, scale = 0, precision = 10)
    public Integer getVal2() {
        return this.val2;
    }

    public void setVal2(Integer val2) {
        this.val2 = val2;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Temp1)) return false;
        final Temp1 temp1 = (Temp1) o;
        return Objects.equals(getId(), temp1.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}