/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.customer_issues.tempdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Temp3 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`temp3`")
public class Temp3 implements Serializable {

    private Integer id;
    private String val4;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`val4`", nullable = true, length = 255)
    public String getVal4() {
        return this.val4;
    }

    public void setVal4(String val4) {
        this.val4 = val4;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Temp3)) return false;
        final Temp3 temp3 = (Temp3) o;
        return Objects.equals(getId(), temp3.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}