/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.customer_issues.tempdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TempTable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`temp_table`")
public class TempTable implements Serializable {

    private String emailId;
    private Integer val1;
    private Integer val2;
    private int id;
    private String tempcolumn;
    private String tempcolumn2;

    @Id
    @Column(name = "`email_id`", nullable = false, length = 255)
    public String getEmailId() {
        return this.emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    @Column(name = "`val1`", nullable = true, scale = 0, precision = 10)
    public Integer getVal1() {
        return this.val1;
    }

    public void setVal1(Integer val1) {
        this.val1 = val1;
    }

    @Column(name = "`val2`", nullable = true, scale = 0, precision = 10)
    public Integer getVal2() {
        return this.val2;
    }

    public void setVal2(Integer val2) {
        this.val2 = val2;
    }

    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "`tempcolumn`", nullable = true, length = 255)
    public String getTempcolumn() {
        return this.tempcolumn;
    }

    public void setTempcolumn(String tempcolumn) {
        this.tempcolumn = tempcolumn;
    }

    @Column(name = "`tempcolumn2`", nullable = true, length = 255)
    public String getTempcolumn2() {
        return this.tempcolumn2;
    }

    public void setTempcolumn2(String tempcolumn2) {
        this.tempcolumn2 = tempcolumn2;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TempTable)) return false;
        final TempTable tempTable = (TempTable) o;
        return Objects.equals(getEmailId(), tempTable.getEmailId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmailId());
    }
}