/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.customer_issues.tempdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.customer_issues.tempdb.Temp2;
import com.customer_issues.tempdb.Temp3;

/**
 * Service object for domain model class {@link Temp3}.
 */
public interface Temp3Service {

    /**
     * Creates a new Temp3. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Temp3 if any.
     *
     * @param temp3 Details of the Temp3 to be created; value cannot be null.
     * @return The newly created Temp3.
     */
    Temp3 create(@Valid Temp3 temp3);


	/**
     * Returns Temp3 by given id if exists.
     *
     * @param temp3Id The id of the Temp3 to get; value cannot be null.
     * @return Temp3 associated with the given temp3Id.
	 * @throws EntityNotFoundException If no Temp3 is found.
     */
    Temp3 getById(Integer temp3Id);

    /**
     * Find and return the Temp3 by given id if exists, returns null otherwise.
     *
     * @param temp3Id The id of the Temp3 to get; value cannot be null.
     * @return Temp3 associated with the given temp3Id.
     */
    Temp3 findById(Integer temp3Id);

	/**
     * Find and return the list of Temp3s by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param temp3Ids The id's of the Temp3 to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Temp3s associated with the given temp3Ids.
     */
    List<Temp3> findByMultipleIds(List<Integer> temp3Ids, boolean orderedReturn);


    /**
     * Updates the details of an existing Temp3. It replaces all fields of the existing Temp3 with the given temp3.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Temp3 if any.
     *
     * @param temp3 The details of the Temp3 to be updated; value cannot be null.
     * @return The updated Temp3.
     * @throws EntityNotFoundException if no Temp3 is found with given input.
     */
    Temp3 update(@Valid Temp3 temp3);


    /**
     * Partially updates the details of an existing Temp3. It updates only the
     * fields of the existing Temp3 which are passed in the temp3Patch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Temp3 if any.
     *
     * @param temp3Id The id of the Temp3 to be deleted; value cannot be null.
     * @param temp3Patch The partial data of Temp3 which is supposed to be updated; value cannot be null.
     * @return The updated Temp3.
     * @throws EntityNotFoundException if no Temp3 is found with given input.
     */
    Temp3 partialUpdate(Integer temp3Id, Map<String, Object> temp3Patch);

    /**
     * Deletes an existing Temp3 with the given id.
     *
     * @param temp3Id The id of the Temp3 to be deleted; value cannot be null.
     * @return The deleted Temp3.
     * @throws EntityNotFoundException if no Temp3 found with the given id.
     */
    Temp3 delete(Integer temp3Id);

    /**
     * Deletes an existing Temp3 with the given object.
     *
     * @param temp3 The instance of the Temp3 to be deleted; value cannot be null.
     */
    void delete(Temp3 temp3);

    /**
     * Find all Temp3s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Temp3s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Temp3> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Temp3s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Temp3s.
     *
     * @see Pageable
     * @see Page
     */
    Page<Temp3> findAll(String query, Pageable pageable);

    /**
     * Exports all Temp3s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Temp3s matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Temp3s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Temp3.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated temp2s for given Temp3 id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Temp2 instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Temp2> findAssociatedTemp2s(Integer id, Pageable pageable);

}