/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.customer_issues.tempdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.customer_issues.tempdb.Temp1;
import com.customer_issues.tempdb.Temp2;

/**
 * Service object for domain model class {@link Temp1}.
 */
public interface Temp1Service {

    /**
     * Creates a new Temp1. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Temp1 if any.
     *
     * @param temp1 Details of the Temp1 to be created; value cannot be null.
     * @return The newly created Temp1.
     */
    Temp1 create(@Valid Temp1 temp1);


	/**
     * Returns Temp1 by given id if exists.
     *
     * @param temp1Id The id of the Temp1 to get; value cannot be null.
     * @return Temp1 associated with the given temp1Id.
	 * @throws EntityNotFoundException If no Temp1 is found.
     */
    Temp1 getById(Integer temp1Id);

    /**
     * Find and return the Temp1 by given id if exists, returns null otherwise.
     *
     * @param temp1Id The id of the Temp1 to get; value cannot be null.
     * @return Temp1 associated with the given temp1Id.
     */
    Temp1 findById(Integer temp1Id);

	/**
     * Find and return the list of Temp1s by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param temp1Ids The id's of the Temp1 to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Temp1s associated with the given temp1Ids.
     */
    List<Temp1> findByMultipleIds(List<Integer> temp1Ids, boolean orderedReturn);


    /**
     * Updates the details of an existing Temp1. It replaces all fields of the existing Temp1 with the given temp1.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Temp1 if any.
     *
     * @param temp1 The details of the Temp1 to be updated; value cannot be null.
     * @return The updated Temp1.
     * @throws EntityNotFoundException if no Temp1 is found with given input.
     */
    Temp1 update(@Valid Temp1 temp1);


    /**
     * Partially updates the details of an existing Temp1. It updates only the
     * fields of the existing Temp1 which are passed in the temp1Patch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Temp1 if any.
     *
     * @param temp1Id The id of the Temp1 to be deleted; value cannot be null.
     * @param temp1Patch The partial data of Temp1 which is supposed to be updated; value cannot be null.
     * @return The updated Temp1.
     * @throws EntityNotFoundException if no Temp1 is found with given input.
     */
    Temp1 partialUpdate(Integer temp1Id, Map<String, Object> temp1Patch);

    /**
     * Deletes an existing Temp1 with the given id.
     *
     * @param temp1Id The id of the Temp1 to be deleted; value cannot be null.
     * @return The deleted Temp1.
     * @throws EntityNotFoundException if no Temp1 found with the given id.
     */
    Temp1 delete(Integer temp1Id);

    /**
     * Deletes an existing Temp1 with the given object.
     *
     * @param temp1 The instance of the Temp1 to be deleted; value cannot be null.
     */
    void delete(Temp1 temp1);

    /**
     * Find all Temp1s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Temp1s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Temp1> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Temp1s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Temp1s.
     *
     * @see Pageable
     * @see Page
     */
    Page<Temp1> findAll(String query, Pageable pageable);

    /**
     * Exports all Temp1s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Temp1s matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Temp1s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Temp1.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated temp2s for given Temp1 id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Temp2 instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Temp2> findAssociatedTemp2s(Integer id, Pageable pageable);

}